global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/auth/api/metrics'
    static_configs:
      - targets: ['auth-service:4001']

  # - job_name: 'notification-service'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['notification-service:4002']