global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/auth/api/metrics'
    static_configs:
      - targets: ['auth-service:4001']
        labels:
          service: 'auth-service'

  # - job_name: 'notification-service'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['notification-service:4002']
  #       labels:
  #         service: 'notification-service'